create_vpc: false
port_expose: 80
root_domain: "burrows-cloud.com"
hosted_zone: "ZIM8ZVHCGKKCA"
ttl: 300
state: present
health_check: "/health"
cpu_limit: 256
mem_limit: 512
desired_count: 1
use_hosted_zone: false