---
- name: define project region if specific
  set_fact: project_region="{{ project_env[current_env].project_region }}"
  when: project_env[current_env].project_region is defined

- name: check default vpc if not defined
  command: aws ec2 describe-vpcs --profile {{ current_env }} --region "{{ project_region }}" --filters Name=isDefault,Values=true --output text --query Vpcs[].VpcId
  register: default_vpc
  when: use_vpc is not defined

- name: check default subnets if not defined
  shell: aws ec2 describe-subnets --profile {{ current_env }} --region "{{ project_region }}" --filters Name=default-for-az,Values=true Name=vpc-id,Values="{{ default_vpc.stdout }}" --output text --query Subnets[].SubnetId | tr "\\t" ", "
  register: subnets
  when: use_subnets is not defined

- name: set default vpc if not defined
  set_fact: use_vpc="{{ default_vpc.stdout }}"
  when: use_vpc is not defined

- name: set default subnet if not defined
  set_fact: use_subnets="{{ subnets.stdout }}"
  when: use_subnets is not defined

- name: secrets workaround
  shell: aws secretsmanager get-secret-value --secret-id /{{ project_name }}/{{ current_env }}/{{ application_name }}/{{ item }} --output text --query SecretString
  when: secret_vars is defined
  with_items: "{{ secret_vars }}"
  register: secret_result
  no_log: True

- name: ecs manager
  local_action:
    module: cloudformation
    aws_profile: "{{ current_env }}"
    disable_rollback: true
    stack_name: "{{ project_name }}-{{ application_name }}-{{ current_env }}-ansible-managed"
    state: "{{ state }}"
    region: "{{ project_region }}"
    template_body: "{{ lookup('template', 'ecs-fargate.yaml.j2') }}"
    template_parameters:
        ProjectName: "{{ project_name }}"
        EnvironmentName: "{{ current_env }}"
        VPC: "{{ use_vpc }}"
        Subnets: "{{ use_subnets }}"
        PortExpose: "{{ port_expose }}"
        AllowedIp: "{{ project_env[current_env].allowed_ip }}"
        ApplicationName: "{{ application_name }}"
        RootDomain: "{{ root_domain }}"
        BranchName: "{{ branch_name }}"
        BuildNumber: "{{ build_number }}"
        RootAccount: "{{ root_account }}"
        ExistHostedZone: "{{ hosted_zone }}"
        CpuLimit: "{{ cpu_limit }}"
        MemoryLimit: "{{ mem_limit }}"
        DesiredCount: "{{ desired_count }}"
        HealthCheckPath: "{{ health_check }}"
    tags: 
        Stack: "{{ project_name }}-{{ current_env }}-ecs-ansible"
        Managed by: Managed by Ansible