Description: >
  To manage hosted zones on Route 53 and create domains per services

Parameters:
  ProjectName:
    Description: Project Name
    Type: String

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  ApplicationName:
    Description: Application Name
    Type: String

  RootDomain:
    Description: Root domain to be used for this Project
    Type: String
  
  Ttl:
    Description: Time-to-live TTL
    Type: String
    Default: 300

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        - Comment: !Sub ${EnvironmentName}-${ProjectName}
      Name: !Sub ${EnvironmentName}.${ProjectName}.${RootDomain}.

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub ${ApplicationName}.${EnvironmentName}.${ProjectName}.${RootDomain}.
      Comment: !Sub ${ProjectName}-${ApplicationName}-${EnvironmentName}
      Type: CNAME
      TTL: !Ref Ttl
      HostedZoneId: !Ref HostedZone

Outputs:
  Domain:
    Description: Domain record for listeners configuration
    Value: !Ref RecordSet
